name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core TEST
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies TEST
      run: dotnet restore
    - name: Build TEST
      run: dotnet build --configuration Release --no-restore
    - name: Test TEST
      run: dotnet test --no-restore --verbosity normal
