name: .NET Core

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core TEST
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies TEST
      run: dotnet restore src/PettingAnimals/PettingAnimals.csproj --verbosity normal
    - name: Build TEST
      run: dotnet build src/PettingAnimals/PettingAnimals.csproj --no-restore
    - name: Test TEST
      run: dotnet test test/ExampleTests/ExampleTests.csproj
